name: ReviewGenie

on: 
  pull_request:
    types: [opened, synchronize, reopened]

jobs: 
  review_pr: 
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with: 
          node-version: 18
        
      - name: Install Dependencies
        run: npm install @octokit/rest @google/generative-ai discord.js dotenv

      - name: Run ReviewGenie
        run: node index.js
        env: 
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID }}
          REPOSITORY_NAME: ${{ github.event.repository.name }}
          REPOSITORY_OWNER:  ${{ github.repository_owner }}
          PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}

